FROM node:latest

# Set up nginx to proxy requests.
# Should probably switch to express since we are in a node container anyway.
RUN apt-get update; apt-get -y install nginx

RUN npm install --global gulp

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN npm install
RUN gulp

EXPOSE 8080

CMD ["node", "server.js"]