version: "2"

services:
    backend:
      build:
        context: ./processing
        dockerfile: Dockerfile.processing
      volumes:
        # App files and config
        - ./processing/config/uwsgi.ini:/etc/uwsgi/uwsgi.ini:ro
        - ./processing/config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
        - ./processing/app/main.py:/app/main.py:ro
        - ./processing/data:/app/data:rw
        # Library
        - ./processing:/usr/local/lib/python3.6/site-packages/processing:ro
        # Linters and Tests
        - ./processing/tests/:/app/tests:ro
        # Entrypoint
        - ./processing/config/entrypoint.sh:/entrypoint.sh:ro
      ports:
        - 8081:8081

    web:
      volumes:
        - ./frontend/:/usr/src/app/:rw
      build:
        context: ./frontend
        dockerfile: Dockerfile.web
      ports:
        - 8080:8080
